//! Synthetic fixtures. Nothing here is read from disk: every image a test
//! decodes is generated by the code below.

#![allow(dead_code, reason = "each test binary uses a different subset")]

use std::io::{Cursor, Write};

/// A `w × h` straight RGBA8 image with a deterministic, asymmetric pattern:
/// every pixel differs from its mirror images, so orientation mistakes show.
pub fn pattern(w: u32, h: u32, alpha: bool) -> image::RgbaImage {
    image::RgbaImage::from_fn(w, h, |x, y| {
        let a = if alpha {
            ((x * 255) / w.max(1)) as u8
        } else {
            255
        };
        image::Rgba([
            (x * 37 + y * 11) as u8,
            (y * 53 + 7) as u8,
            ((x ^ y) * 29) as u8,
            a,
        ])
    })
}

/// Encodes `img` in `format` with the `image` crate's encoders.
pub fn encode(img: &image::DynamicImage, format: image::ImageFormat) -> Vec<u8> {
    let mut out = Cursor::new(Vec::new());
    img.write_to(&mut out, format).expect("encode fixture");
    out.into_inner()
}

/// CRC-32 (IEEE) for hand-built PNG chunks.
pub fn crc32(bytes: &[u8]) -> u32 {
    let mut c = flate2::Crc::new();
    c.update(bytes);
    c.sum()
}

/// One PNG chunk: length, type, data, CRC.
pub fn png_chunk(kind: &[u8; 4], data: &[u8]) -> Vec<u8> {
    let mut v = Vec::with_capacity(data.len() + 12);
    v.extend_from_slice(&(data.len() as u32).to_be_bytes());
    v.extend_from_slice(kind);
    v.extend_from_slice(data);
    let mut crc_in = kind.to_vec();
    crc_in.extend_from_slice(data);
    v.extend_from_slice(&crc32(&crc_in).to_be_bytes());
    v
}

/// A PNG with an arbitrary IHDR and IDAT payload.
pub fn png_raw(w: u32, h: u32, bit_depth: u8, colour: u8, idat: &[u8]) -> Vec<u8> {
    let mut ihdr = Vec::new();
    ihdr.extend_from_slice(&w.to_be_bytes());
    ihdr.extend_from_slice(&h.to_be_bytes());
    ihdr.extend_from_slice(&[bit_depth, colour, 0, 0, 0]);
    let mut v = b"\x89PNG\r\n\x1a\n".to_vec();
    v.extend(png_chunk(b"IHDR", &ihdr));
    v.extend(png_chunk(b"IDAT", idat));
    v.extend(png_chunk(b"IEND", &[]));
    v
}

/// zlib-compresses `data`.
pub fn zlib(data: &[u8]) -> Vec<u8> {
    let mut e = flate2::write::ZlibEncoder::new(Vec::new(), flate2::Compression::best());
    e.write_all(data).expect("zlib");
    e.finish().expect("zlib")
}

/// A minimal little-endian TIFF/EXIF structure holding one Orientation tag.
pub fn exif_tiff(orientation: u16) -> Vec<u8> {
    let mut t = b"II*\0".to_vec();
    t.extend_from_slice(&8u32.to_le_bytes()); // IFD0 offset
    t.extend_from_slice(&1u16.to_le_bytes()); // one entry
    t.extend_from_slice(&0x0112u16.to_le_bytes()); // Orientation
    t.extend_from_slice(&3u16.to_le_bytes()); // SHORT
    t.extend_from_slice(&1u32.to_le_bytes()); // count
    t.extend_from_slice(&orientation.to_le_bytes());
    t.extend_from_slice(&[0, 0]); // value padding
    t.extend_from_slice(&0u32.to_le_bytes()); // no next IFD
    t
}

/// Inserts an `eXIf` chunk right after IHDR.
pub fn png_with_exif(png: &[u8], orientation: u16) -> Vec<u8> {
    let ihdr_end = 8 + 12 + 13;
    let mut v = png[..ihdr_end].to_vec();
    v.extend(png_chunk(b"eXIf", &exif_tiff(orientation)));
    v.extend_from_slice(&png[ihdr_end..]);
    v
}

/// Inserts an APP1 `Exif` segment right after SOI.
pub fn jpeg_with_exif(jpeg: &[u8], orientation: u16) -> Vec<u8> {
    let mut payload = b"Exif\0\0".to_vec();
    payload.extend(exif_tiff(orientation));
    let mut v = jpeg[..2].to_vec();
    v.extend_from_slice(&[0xFF, 0xE1]);
    v.extend_from_slice(&((payload.len() + 2) as u16).to_be_bytes());
    v.extend(payload);
    v.extend_from_slice(&jpeg[2..]);
    v
}

/// Stores `upright` so that displaying it with EXIF `orientation` shows
/// `upright` again: the inverse of the display transform.
pub fn store_for_orientation(upright: &image::RgbaImage, orientation: u16) -> image::RgbaImage {
    use image::imageops::{flip_horizontal, flip_vertical, rotate90, rotate180, rotate270};
    match orientation {
        2 => flip_horizontal(upright),
        3 => rotate180(upright),
        4 => flip_vertical(upright),
        // 5 is its own inverse (transpose).
        5 => flip_horizontal(&rotate90(upright)),
        6 => rotate270(upright),
        // 7 is its own inverse (anti-transpose).
        7 => flip_horizontal(&rotate270(upright)),
        8 => rotate90(upright),
        _ => upright.clone(),
    }
}

/// Peak resident set, in KiB, since the last [`reset_peak_rss`]. `None`
/// off Linux.
pub fn peak_rss_kib() -> Option<u64> {
    let s = std::fs::read_to_string("/proc/self/status").ok()?;
    s.lines()
        .find(|l| l.starts_with("VmHWM:"))?
        .split_whitespace()
        .nth(1)?
        .parse()
        .ok()
}

/// Current resident set, in KiB.
pub fn rss_kib() -> Option<u64> {
    let s = std::fs::read_to_string("/proc/self/status").ok()?;
    s.lines()
        .find(|l| l.starts_with("VmRSS:"))?
        .split_whitespace()
        .nth(1)?
        .parse()
        .ok()
}

/// Resets the peak-RSS watermark (Linux `clear_refs` value 5). Returns
/// whether it worked.
pub fn reset_peak_rss() -> bool {
    std::fs::write("/proc/self/clear_refs", "5").is_ok()
}
