//! The feature corpus: every scene the golden-image gates run over.
//!
//! The scenes are generated by code rather than stored, so that adding a
//! feature adds its cases automatically and nobody has to hand-draw a
//! regression test. The matrix is deliberately exhaustive where the
//! research says the risk is: every gradient shape × repeat mode ×
//! mapping, every blend family at two transparencies, every cap and join,
//! the fill rules, clipping, nested layers and image sampling.
//!
//! Each case is rendered at 96 × 96 with one point per pixel, which is
//! small enough to commit 120 golden PNGs and large enough for an
//! antialiased edge to have somewhere to go.

use xarast_color::Rgba8;
use xarast_geom::{Cap, DashPattern, FillRule, Join, Mp, Path, Point, Rect, StrokeStyle};

use crate::backend::cpu::Resolver;
use crate::blend::{ALL_FAMILIES, BlendFamily, TranspSource, Transparency};
use crate::display_list::ViewParams;
use crate::paint::{
    ALL_MAPPINGS, ALL_REPEATS, ALL_SHAPES, GradMapping, GradRamp, GradShape, ImageRef, MappingKind,
    Paint, Repeat,
};
use crate::path::PathRef;
use crate::precision::{Point64, Transform2D};
use crate::ramp::{EffectSpace, Profile, RampLength, Stop, TranspStop, build_transparency_ramp};
use crate::scene::{CacheHint, LayerKind, RenderQuality, Scene, SceneBuilder, SceneNodeId};

/// The edge length of every corpus scene, in pixels.
pub const CASE_SIZE: u32 = 96;

/// One named scene, ready to render.
#[derive(Debug)]
pub struct Case {
    /// A filename-safe name; the golden is `<name>.png`.
    pub name: String,
    /// What to draw.
    pub scene: Scene,
    /// The ramps and images it refers to.
    pub resolver: Resolver,
    /// How to look at it.
    pub view: ViewParams,
}

fn view() -> ViewParams {
    // One document point per device pixel keeps every coordinate in the
    // corpus readable.
    ViewParams::new(
        CASE_SIZE,
        CASE_SIZE,
        Transform2D::scale(1.0 / f64::from(Mp::PER_PT)),
        RenderQuality::Final,
    )
}

fn pt(x: f64, y: f64) -> Point {
    Point::new(Mp::from_pt(x), Mp::from_pt(y))
}

/// A continuous point in **document** units, from a value in points.
///
/// Paint mappings live in document space, like the geometry they follow;
/// forgetting that and writing device pixels here produces a gradient frame
/// a thousandth of a pixel across, which renders as a single flat colour.
fn dpt(x: f64, y: f64) -> Point64 {
    Point64::new(x * f64::from(Mp::PER_PT), y * f64::from(Mp::PER_PT))
}

fn rect_path(x0: f64, y0: f64, x1: f64, y1: f64) -> PathRef {
    let mut b = Path::builder();
    b.rect(Rect::new(pt(x0, y0), pt(x1, y1)));
    PathRef::new(b.build())
}

fn star_path() -> PathRef {
    let mut b = Path::builder();
    let (cx, cy, r0, r1) = (48.0, 48.0, 40.0, 16.0);
    for i in 0..10 {
        let a = std::f64::consts::TAU * f64::from(i) / 10.0 - std::f64::consts::FRAC_PI_2;
        let r = if i % 2 == 0 { r0 } else { r1 };
        let p = pt(cx + r * a.cos(), cy + r * a.sin());
        if i == 0 {
            b.move_to(p);
        } else {
            b.line_to(p);
        }
    }
    b.close();
    PathRef::new(b.build())
}

fn zigzag_path() -> PathRef {
    let mut b = Path::builder();
    b.move_to(pt(12.0, 20.0));
    b.line_to(pt(48.0, 76.0));
    b.line_to(pt(84.0, 20.0));
    PathRef::new(b.build())
}

fn curve_path() -> PathRef {
    let mut b = Path::builder();
    b.move_to(pt(8.0, 48.0));
    b.cubic_to(pt(28.0, 8.0), pt(68.0, 88.0), pt(88.0, 48.0));
    PathRef::new(b.build())
}

fn white() -> Rgba8 {
    Rgba8::WHITE
}

fn rgb(r: u8, g: u8, b: u8) -> Rgba8 {
    Rgba8 { r, g, b, a: 255 }
}

/// A background so that blend families have something to read.
fn backdrop(b: &mut SceneBuilder<'_>) {
    b.fill(
        SceneNodeId(0),
        &rect_path(0.0, 0.0, 96.0, 96.0),
        FillRule::NonZero,
        Paint::Solid(white()),
    );
    // Three bands of saturated colour: destination-reading families need a
    // destination with chroma, or Saturation and Hue test nothing.
    for (i, c) in [rgb(220, 60, 40), rgb(40, 170, 90), rgb(50, 90, 210)]
        .into_iter()
        .enumerate()
    {
        let y0 = f64::from(u8::try_from(i).unwrap_or(0)) * 32.0;
        b.fill(
            SceneNodeId(1 + i as u64),
            &rect_path(0.0, y0, 96.0, y0 + 32.0),
            FillRule::NonZero,
            Paint::Solid(c),
        );
    }
}

/// Centred on the canvas, so that a conical gradient sweeps a whole turn
/// and a radial or diamond one is seen from its middle. An off-centre frame
/// would leave four of the six shapes showing a corner of themselves.
fn affine_mapping() -> GradMapping {
    GradMapping::Affine {
        a: dpt(48.0, 48.0),
        b: dpt(48.0, 88.0),
        c: dpt(88.0, 48.0),
    }
}

fn perspective_mapping() -> GradMapping {
    GradMapping::Perspective {
        a: dpt(48.0, 48.0),
        b: dpt(36.0, 92.0),
        c: dpt(90.0, 40.0),
        d: dpt(84.0, 84.0),
    }
}

fn mapping_of(kind: MappingKind) -> GradMapping {
    match kind {
        MappingKind::Affine => affine_mapping(),
        MappingKind::Perspective => perspective_mapping(),
    }
}

fn shape_name(s: GradShape) -> &'static str {
    match s {
        GradShape::Linear => "linear",
        GradShape::Radial => "radial",
        GradShape::Conical => "conical",
        GradShape::Diamond => "diamond",
        GradShape::Mesh3 => "mesh3",
        GradShape::Mesh4 => "mesh4",
    }
}

fn repeat_name(r: Repeat) -> &'static str {
    match r {
        Repeat::Simple => "simple",
        Repeat::Repeat => "repeat",
        Repeat::Mirror => "mirror",
        Repeat::RepeatHq => "repeathq",
    }
}

fn mapping_name(m: MappingKind) -> &'static str {
    match m {
        MappingKind::Affine => "affine",
        MappingKind::Perspective => "perspective",
    }
}

fn family_name(f: BlendFamily) -> &'static str {
    match f {
        BlendFamily::Mix => "mix",
        BlendFamily::StainedGlass => "stainedglass",
        BlendFamily::Bleach => "bleach",
        BlendFamily::Contrast => "contrast",
        BlendFamily::Saturation => "saturation",
        BlendFamily::Darken => "darken",
        BlendFamily::Lighten => "lighten",
        BlendFamily::Brightness => "brightness",
        BlendFamily::Luminosity => "luminosity",
        BlendFamily::Hue => "hue",
        BlendFamily::Bevel => "bevel",
        BlendFamily::None => "none",
    }
}

/// Every gradient cell that is legal for its shape: 6 × 4 × 2 = 48.
///
/// Every cell is legal — a mesh ignores the repeat mode rather than
/// forbidding it, and both mappings apply to every shape — so the count is
/// the full product, which is what `gradient_matrix` asserts.
fn gradient_cases() -> Vec<Case> {
    let mut out = Vec::new();
    for shape in ALL_SHAPES {
        for repeat in ALL_REPEATS {
            for mk in ALL_MAPPINGS {
                let mut scene = Scene::new();
                let mut res = Resolver::new();
                let ramp = res.ramps.intern(
                    &[
                        Stop::new(0.0, rgb(250, 240, 20)),
                        Stop::new(0.45, rgb(230, 30, 120)),
                        Stop::new(1.0, rgb(20, 60, 200)),
                    ],
                    Profile::new(0.2, -0.3),
                    EffectSpace::Rgb,
                    if repeat == Repeat::RepeatHq {
                        RampLength::Long
                    } else {
                        RampLength::Short
                    },
                );
                let gramp = match shape {
                    GradShape::Mesh3 => {
                        GradRamp::Mesh3([rgb(250, 240, 20), rgb(230, 30, 120), rgb(20, 60, 200)])
                    }
                    GradShape::Mesh4 => GradRamp::Mesh4([
                        rgb(250, 240, 20),
                        rgb(230, 30, 120),
                        rgb(20, 60, 200),
                        rgb(20, 200, 120),
                    ]),
                    _ => GradRamp::Table(ramp),
                };
                {
                    let mut b = SceneBuilder::begin(&mut scene, RenderQuality::Final);
                    b.fill(
                        SceneNodeId(0),
                        &rect_path(0.0, 0.0, 96.0, 96.0),
                        FillRule::NonZero,
                        Paint::Solid(white()),
                    );
                    b.fill(
                        SceneNodeId(1),
                        &star_path(),
                        FillRule::NonZero,
                        Paint::Gradient {
                            shape,
                            mapping: mapping_of(mk),
                            repeat,
                            ramp: gramp,
                        },
                    );
                    b.finish().expect("balanced");
                }
                out.push(Case {
                    name: format!(
                        "gradient_{}_{}_{}",
                        shape_name(shape),
                        repeat_name(repeat),
                        mapping_name(mk)
                    ),
                    scene,
                    resolver: res,
                    view: view(),
                });
            }
        }
    }
    out
}

/// Every blend family at two transparencies: 24 cases.
fn blend_cases() -> Vec<Case> {
    let mut out = Vec::new();
    for family in ALL_FAMILIES {
        for level in [64u8, 192u8] {
            let mut scene = Scene::new();
            {
                let mut b = SceneBuilder::begin(&mut scene, RenderQuality::Final);
                backdrop(&mut b);
                b.push_transparency(Transparency::flat(family, level));
                b.fill(
                    SceneNodeId(10),
                    &star_path(),
                    FillRule::NonZero,
                    Paint::Solid(rgb(200, 190, 60)),
                );
                b.pop_transparency();
                b.finish().expect("balanced");
            }
            out.push(Case {
                name: format!("blend_{}_{level}", family_name(family)),
                scene,
                resolver: Resolver::new(),
                view: view(),
            });
        }
    }
    out
}

/// Graduated and bitmap-sourced transparency feeding the same families.
fn graduated_transparency_cases() -> Vec<Case> {
    let mut out = Vec::new();
    for (i, family) in [
        BlendFamily::Mix,
        BlendFamily::StainedGlass,
        BlendFamily::Darken,
        BlendFamily::Luminosity,
    ]
    .into_iter()
    .enumerate()
    {
        let mut scene = Scene::new();
        let mut res = Resolver::new();
        let ramp = res.ramps.intern(
            &[Stop::new(0.0, Rgba8::BLACK), Stop::new(1.0, Rgba8::WHITE)],
            Profile::IDENTITY,
            EffectSpace::Rgb,
            RampLength::Long,
        );
        res.transparency_ramps
            .resize(ramp.index() as usize + 1, Vec::new());
        res.transparency_ramps[ramp.index() as usize] = build_transparency_ramp(
            &[
                TranspStop {
                    offset: 0.0,
                    level: 0,
                },
                TranspStop {
                    offset: 1.0,
                    level: 255,
                },
            ],
            Profile::IDENTITY,
            RampLength::Long,
        );
        {
            let mut b = SceneBuilder::begin(&mut scene, RenderQuality::Final);
            backdrop(&mut b);
            b.push_transparency(Transparency {
                family,
                source: TranspSource::Gradient {
                    shape: GradShape::Linear,
                    mapping: affine_mapping(),
                    repeat: Repeat::Simple,
                    ramp,
                },
            });
            b.fill(
                SceneNodeId(10),
                &rect_path(8.0, 8.0, 88.0, 88.0),
                FillRule::NonZero,
                Paint::Solid(rgb(240, 240, 240)),
            );
            b.pop_transparency();
            b.finish().expect("balanced");
        }
        out.push(Case {
            name: format!("transparency_graduated_{}_{i}", family_name(family)),
            scene,
            resolver: res,
            view: view(),
        });
    }
    out
}

/// Caps, joins, dashes, hairlines: 12 cases.
fn stroke_cases() -> Vec<Case> {
    let mut out = Vec::new();
    for cap in [Cap::Butt, Cap::Round, Cap::Square] {
        for join in [Join::Mitre, Join::Round, Join::Bevel] {
            let mut scene = Scene::new();
            {
                let mut b = SceneBuilder::begin(&mut scene, RenderQuality::Final);
                b.fill(
                    SceneNodeId(0),
                    &rect_path(0.0, 0.0, 96.0, 96.0),
                    FillRule::NonZero,
                    Paint::Solid(white()),
                );
                b.stroke(
                    SceneNodeId(1),
                    &zigzag_path(),
                    StrokeStyle {
                        width: Mp::from_pt(12.0),
                        cap_start: cap,
                        cap_end: cap,
                        join,
                        mitre_limit: 4.0,
                        dash: None,
                    },
                    Paint::Solid(rgb(30, 30, 30)),
                );
                b.finish().expect("balanced");
            }
            out.push(Case {
                name: format!("stroke_cap{}_join{}", cap as u8, join as u8),
                scene,
                resolver: Resolver::new(),
                view: view(),
            });
        }
    }
    for (name, style) in [
        (
            "stroke_hairline",
            StrokeStyle {
                width: Mp::ZERO,
                ..StrokeStyle::default()
            },
        ),
        (
            "stroke_dashed",
            StrokeStyle {
                width: Mp::from_pt(6.0),
                dash: Some(DashPattern {
                    elements: vec![Mp::from_pt(8.0), Mp::from_pt(4.0)],
                    ..DashPattern::default()
                }),
                ..StrokeStyle::default()
            },
        ),
        (
            "stroke_thin",
            StrokeStyle {
                width: Mp::from_pt(0.75),
                ..StrokeStyle::default()
            },
        ),
    ] {
        let mut scene = Scene::new();
        {
            let mut b = SceneBuilder::begin(&mut scene, RenderQuality::Final);
            b.fill(
                SceneNodeId(0),
                &rect_path(0.0, 0.0, 96.0, 96.0),
                FillRule::NonZero,
                Paint::Solid(white()),
            );
            b.stroke(
                SceneNodeId(1),
                &curve_path(),
                style,
                Paint::Solid(rgb(20, 60, 160)),
            );
            b.finish().expect("balanced");
        }
        out.push(Case {
            name: name.to_string(),
            scene,
            resolver: Resolver::new(),
            view: view(),
        });
    }
    out
}

/// The fill rules on a self-intersecting star: 4 cases.
fn fill_rule_cases() -> Vec<Case> {
    let mut out = Vec::new();
    let mut b0 = Path::builder();
    // A pentagram: the classic self-intersecting path where the rules differ.
    for i in 0..5 {
        let a = std::f64::consts::TAU * f64::from(i) * 2.0 / 5.0 - std::f64::consts::FRAC_PI_2;
        let p = pt(48.0 + 42.0 * a.cos(), 48.0 + 42.0 * a.sin());
        if i == 0 {
            b0.move_to(p);
        } else {
            b0.line_to(p);
        }
    }
    b0.close();
    let pentagram = PathRef::new(b0.build());
    for rule in [
        FillRule::NonZero,
        FillRule::EvenOdd,
        FillRule::Positive,
        FillRule::Negative,
    ] {
        let mut scene = Scene::new();
        {
            let mut b = SceneBuilder::begin(&mut scene, RenderQuality::Final);
            b.fill(
                SceneNodeId(0),
                &rect_path(0.0, 0.0, 96.0, 96.0),
                FillRule::NonZero,
                Paint::Solid(white()),
            );
            b.fill(
                SceneNodeId(1),
                &pentagram,
                rule,
                Paint::Solid(rgb(180, 40, 90)),
            );
            b.finish().expect("balanced");
        }
        out.push(Case {
            name: format!("fillrule_{}", rule as u8),
            scene,
            resolver: Resolver::new(),
            view: view(),
        });
    }
    out
}

/// Clipping, including nested clips: 3 cases.
fn clip_cases() -> Vec<Case> {
    let mut out = Vec::new();
    for (name, nested) in [("clip_single", false), ("clip_nested", true)] {
        let mut scene = Scene::new();
        {
            let mut b = SceneBuilder::begin(&mut scene, RenderQuality::Final);
            b.fill(
                SceneNodeId(0),
                &rect_path(0.0, 0.0, 96.0, 96.0),
                FillRule::NonZero,
                Paint::Solid(white()),
            );
            b.push_clip(&star_path(), FillRule::NonZero);
            if nested {
                b.push_clip(&rect_path(24.0, 0.0, 96.0, 72.0), FillRule::NonZero);
            }
            b.fill(
                SceneNodeId(1),
                &rect_path(0.0, 0.0, 96.0, 96.0),
                FillRule::NonZero,
                Paint::Solid(rgb(40, 120, 200)),
            );
            if nested {
                b.pop_clip();
            }
            b.pop_clip();
            b.finish().expect("balanced");
        }
        out.push(Case {
            name: name.to_string(),
            scene,
            resolver: Resolver::new(),
            view: view(),
        });
    }
    // A clip that excludes everything must draw nothing, which is the case
    // that catches an inverted mask.
    let mut scene = Scene::new();
    {
        let mut b = SceneBuilder::begin(&mut scene, RenderQuality::Final);
        b.fill(
            SceneNodeId(0),
            &rect_path(0.0, 0.0, 96.0, 96.0),
            FillRule::NonZero,
            Paint::Solid(white()),
        );
        b.push_clip(&rect_path(200.0, 200.0, 220.0, 220.0), FillRule::NonZero);
        b.fill(
            SceneNodeId(1),
            &rect_path(0.0, 0.0, 96.0, 96.0),
            FillRule::NonZero,
            Paint::Solid(Rgba8::BLACK),
        );
        b.pop_clip();
        b.finish().expect("balanced");
    }
    out.push(Case {
        name: "clip_empty".to_string(),
        scene,
        resolver: Resolver::new(),
        view: view(),
    });
    out
}

/// Nested offscreen layers: 4 cases.
fn layer_cases() -> Vec<Case> {
    let mut out = Vec::new();
    for (name, kind, family) in [
        ("layer_plain", LayerKind::Plain, BlendFamily::Mix),
        ("layer_isolated", LayerKind::Isolated, BlendFamily::Mix),
        (
            "layer_dstread",
            LayerKind::DestinationReading,
            BlendFamily::StainedGlass,
        ),
        ("layer_nested", LayerKind::Isolated, BlendFamily::Bleach),
    ] {
        let mut scene = Scene::new();
        {
            let mut b = SceneBuilder::begin(&mut scene, RenderQuality::Final);
            backdrop(&mut b);
            b.push_layer(kind, Transparency::flat(family, 96));
            b.fill(
                SceneNodeId(10),
                &rect_path(12.0, 12.0, 60.0, 60.0),
                FillRule::NonZero,
                Paint::Solid(rgb(240, 220, 60)),
            );
            if name == "layer_nested" {
                b.push_layer(
                    LayerKind::Isolated,
                    Transparency::flat(BlendFamily::Mix, 64),
                );
                b.fill(
                    SceneNodeId(11),
                    &rect_path(40.0, 40.0, 88.0, 88.0),
                    FillRule::NonZero,
                    Paint::Solid(rgb(30, 160, 210)),
                );
                b.pop_layer();
            }
            b.pop_layer();
            b.finish().expect("balanced");
        }
        out.push(Case {
            name: name.to_string(),
            scene,
            resolver: Resolver::new(),
            view: view(),
        });
    }
    out
}

/// A small checkerboard image, for the image-fill cases.
fn checker_image() -> ImageRef {
    let (w, h) = (8u32, 8u32);
    let mut data = Vec::with_capacity((w * h * 4) as usize);
    for y in 0..h {
        for x in 0..w {
            let on = (x / 2 + y / 2) % 2 == 0;
            let (r, g, b) = if on { (240, 80, 40) } else { (20, 40, 120) };
            data.extend_from_slice(&[r, g, b, 255]);
        }
    }
    ImageRef::new(w, h, data)
}

/// Image fills: sampling, repeat modes, contone and adjustment. 12 cases.
fn image_cases() -> Vec<Case> {
    let mut out = Vec::new();
    for filter in [
        crate::paint::Filter::Nearest,
        crate::paint::Filter::Bilinear,
        crate::paint::Filter::HighQuality,
    ] {
        for repeat in ALL_REPEATS {
            let mut scene = Scene::new();
            let mut res = Resolver::new();
            let img = res.images.insert(checker_image());
            {
                let mut b = SceneBuilder::begin(&mut scene, RenderQuality::Final);
                b.fill(
                    SceneNodeId(0),
                    &rect_path(0.0, 0.0, 96.0, 96.0),
                    FillRule::NonZero,
                    Paint::Solid(white()),
                );
                b.fill(
                    SceneNodeId(1),
                    &star_path(),
                    FillRule::NonZero,
                    Paint::Image {
                        image: img,
                        // A mapping smaller than the shape, so the repeat
                        // mode has something to do.
                        mapping: GradMapping::Affine {
                            a: dpt(24.0, 24.0),
                            b: dpt(24.0, 56.0),
                            c: dpt(56.0, 24.0),
                        },
                        repeat,
                        filter,
                        contone: None,
                        adjust: crate::paint::BitmapAdjust::default(),
                    },
                );
                b.finish().expect("balanced");
            }
            out.push(Case {
                name: format!("image_{}_{}", filter as u8, repeat_name(repeat)),
                scene,
                resolver: res,
                view: view(),
            });
        }
    }
    out
}

/// The antialiasing probes, which are also the cases the AA report reads.
fn aa_cases() -> Vec<Case> {
    let mut out = Vec::new();
    for (name, deg) in [
        ("aa_edge_0p5", 0.5f64),
        ("aa_edge_2", 2.0),
        ("aa_edge_45", 45.0),
    ] {
        let mut scene = Scene::new();
        {
            let mut b = SceneBuilder::begin(&mut scene, RenderQuality::Final);
            b.fill(
                SceneNodeId(0),
                &rect_path(0.0, 0.0, 96.0, 96.0),
                FillRule::NonZero,
                Paint::Solid(white()),
            );
            // The half-plane below a line through the centre at `deg`.
            // Constructing it from the centre outwards keeps the edge on
            // the canvas at every angle; extending it to the right by the
            // tangent would put a 45 degree edge off the top.
            let (dx, dy) = (deg.to_radians().cos(), deg.to_radians().sin());
            let (cx, cy) = (48.0, 48.0);
            let far = 400.0;
            let mut p = Path::builder();
            p.move_to(pt(cx - far * dx, cy - far * dy));
            p.line_to(pt(cx + far * dx, cy + far * dy));
            p.line_to(pt(cx + far * dx - far * dy, cy + far * dy + far * dx));
            p.line_to(pt(cx - far * dx - far * dy, cy - far * dy + far * dx));
            p.close();
            b.fill(
                SceneNodeId(1),
                &PathRef::new(p.build()),
                FillRule::NonZero,
                Paint::Solid(Rgba8::BLACK),
            );
            b.finish().expect("balanced");
        }
        out.push(Case {
            name: name.to_string(),
            scene,
            resolver: Resolver::new(),
            view: view(),
        });
    }
    // Two shapes sharing an exact edge: the conflation probe.
    let mut scene = Scene::new();
    {
        let mut b = SceneBuilder::begin(&mut scene, RenderQuality::Final);
        b.fill(
            SceneNodeId(0),
            &rect_path(0.0, 0.0, 96.0, 96.0),
            FillRule::NonZero,
            Paint::Solid(white()),
        );
        let mut left = Path::builder();
        left.move_to(pt(16.0, 16.0));
        left.line_to(pt(64.0, 80.0));
        left.line_to(pt(8.0, 80.0));
        left.close();
        let mut right = Path::builder();
        right.move_to(pt(16.0, 16.0));
        right.line_to(pt(64.0, 80.0));
        right.line_to(pt(88.0, 16.0));
        right.close();
        let c = rgb(30, 30, 30);
        b.fill(
            SceneNodeId(1),
            &PathRef::new(left.build()),
            FillRule::NonZero,
            Paint::Solid(c),
        );
        b.fill(
            SceneNodeId(2),
            &PathRef::new(right.build()),
            FillRule::NonZero,
            Paint::Solid(c),
        );
        b.finish().expect("balanced");
    }
    out.push(Case {
        name: "aa_seam".to_string(),
        scene,
        resolver: Resolver::new(),
        view: view(),
    });
    // Hairlines at many angles.
    let mut scene = Scene::new();
    {
        let mut b = SceneBuilder::begin(&mut scene, RenderQuality::Final);
        b.fill(
            SceneNodeId(0),
            &rect_path(0.0, 0.0, 96.0, 96.0),
            FillRule::NonZero,
            Paint::Solid(white()),
        );
        for i in 0..12 {
            let a = std::f64::consts::PI * f64::from(i) / 12.0;
            let mut p = Path::builder();
            p.move_to(pt(48.0 - 44.0 * a.cos(), 48.0 - 44.0 * a.sin()));
            p.line_to(pt(48.0 + 44.0 * a.cos(), 48.0 + 44.0 * a.sin()));
            b.stroke(
                SceneNodeId(10 + i as u64),
                &PathRef::new(p.build()),
                StrokeStyle {
                    width: Mp::from_pt(0.2),
                    ..StrokeStyle::default()
                },
                Paint::Solid(Rgba8::BLACK),
            );
        }
        b.finish().expect("balanced");
    }
    out.push(Case {
        name: "aa_hairlines".to_string(),
        scene,
        resolver: Resolver::new(),
        view: view(),
    });
    out
}

/// Structural cases: groups, transforms, draft quality, an empty scene.
fn structure_cases() -> Vec<Case> {
    let mut out = Vec::new();
    for (name, quality) in [
        ("structure_draft", RenderQuality::Draft),
        ("structure_final", RenderQuality::Final),
    ] {
        let mut scene = Scene::new();
        {
            let mut b = SceneBuilder::begin(&mut scene, quality);
            b.fill(
                SceneNodeId(0),
                &rect_path(0.0, 0.0, 96.0, 96.0),
                FillRule::NonZero,
                Paint::Solid(white()),
            );
            b.push_group(
                SceneNodeId(1),
                Transform2D::translate(8_000.0, 4_000.0),
                CacheHint::Always,
            );
            b.fill(
                SceneNodeId(2),
                &curve_path(),
                FillRule::NonZero,
                Paint::Solid(rgb(90, 160, 40)),
            );
            b.pop_group();
            b.finish().expect("balanced");
        }
        let mut v = view();
        v.quality = quality;
        out.push(Case {
            name: name.to_string(),
            scene,
            resolver: Resolver::new(),
            view: v,
        });
    }
    // A rotated, scaled group: the transform composition case.
    let mut scene = Scene::new();
    {
        let mut b = SceneBuilder::begin(&mut scene, RenderQuality::Final);
        b.fill(
            SceneNodeId(0),
            &rect_path(0.0, 0.0, 96.0, 96.0),
            FillRule::NonZero,
            Paint::Solid(white()),
        );
        b.push_group(
            SceneNodeId(1),
            Transform2D::rotate(0.4).then(Transform2D::scale(0.7)),
            CacheHint::Auto,
        );
        b.fill(
            SceneNodeId(2),
            &star_path(),
            FillRule::NonZero,
            Paint::Solid(rgb(200, 120, 20)),
        );
        b.pop_group();
        b.finish().expect("balanced");
    }
    out.push(Case {
        name: "structure_transformed".to_string(),
        scene,
        resolver: Resolver::new(),
        view: view(),
    });
    // An empty scene: the case that catches a backend that assumes work.
    let mut scene = Scene::new();
    {
        let b = SceneBuilder::begin(&mut scene, RenderQuality::Final);
        b.finish().expect("balanced");
    }
    out.push(Case {
        name: "structure_empty".to_string(),
        scene,
        resolver: Resolver::new(),
        view: view(),
    });
    out
}

/// Every case in the feature corpus.
///
/// At least 120, which is the phase's gate; the exact count is asserted by
/// `tests/golden_cpu.rs` so that a case cannot be deleted by accident.
#[must_use]
pub fn all_cases() -> Vec<Case> {
    let mut out = Vec::new();
    out.extend(gradient_cases());
    out.extend(blend_cases());
    out.extend(graduated_transparency_cases());
    out.extend(stroke_cases());
    out.extend(fill_rule_cases());
    out.extend(clip_cases());
    out.extend(layer_cases());
    out.extend(image_cases());
    out.extend(aa_cases());
    out.extend(structure_cases());
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    #[test]
    fn the_corpus_meets_the_phase_gate_of_120_scenes() {
        let cases = all_cases();
        assert!(
            cases.len() >= 120,
            "the corpus has {} cases, the gate is 120",
            cases.len()
        );
    }

    #[test]
    fn every_case_name_is_unique_and_filename_safe() {
        let cases = all_cases();
        let mut seen = HashSet::new();
        for c in &cases {
            assert!(seen.insert(c.name.clone()), "duplicate case {}", c.name);
            assert!(
                c.name
                    .chars()
                    .all(|ch| ch.is_ascii_alphanumeric() || ch == '_'),
                "case name {} is not filename safe",
                c.name
            );
        }
    }

    #[test]
    fn the_gradient_matrix_is_complete() {
        let cases = gradient_cases();
        assert_eq!(cases.len(), 6 * 4 * 2);
        for shape in ALL_SHAPES {
            for repeat in ALL_REPEATS {
                for mk in ALL_MAPPINGS {
                    let name = format!(
                        "gradient_{}_{}_{}",
                        shape_name(shape),
                        repeat_name(repeat),
                        mapping_name(mk)
                    );
                    assert!(
                        cases.iter().any(|c| c.name == name),
                        "missing gradient cell {name}"
                    );
                }
            }
        }
    }

    #[test]
    fn every_blend_family_appears() {
        let cases = blend_cases();
        assert_eq!(cases.len(), 24);
        for f in ALL_FAMILIES {
            assert!(
                cases
                    .iter()
                    .any(|c| c.name.starts_with(&format!("blend_{}_", family_name(f)))),
                "missing family {f:?}"
            );
        }
    }
}
