[package]
name = "xarast-io"
description = "Import and export filters for Xarast (SVG, PNG, JPEG, PDF)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
xarast-doc = { path = "../xarast-doc" }
xarast-image = { path = "../xarast-image" }
xarast-render = { path = "../xarast-render" }
