//! Passes 4 and 5 of `research/06 §4.5.1`: attribute hoisting and CSS paint
//! classes.
//!
//! The walk does not write an element's paint as it goes. It writes the
//! rest of the start tag and leaves a **slot** at the end of it: a small
//! array of interned property values. Every `<g>` gets a slot too. When a
//! `<g>` closes, the properties all its children agree on move into its
//! slot (pass 4); when the walk is over, slots whose remaining set is shared
//! widely enough become `class="cN"` (pass 5); then the body is copied out
//! with each slot expanded in place. Nothing is parsed back.
//!
//! # The contract the reader relies on (`docs/memory/xarast-format.md`)
//!
//! - **Hoisted properties** are the SVG paint properties in [`PROPS`], all of
//!   which SVG inherits, and the two paint twins `xarast:fill-ref` and
//!   `xarast:stroke-ref`, which the profile declares inherited the same way:
//!   an element's value is its own, else its nearest ancestor's, else none.
//! - A property is hoisted to a `<g>` only when **every** child that paints
//!   (an ink element, or a `<g>` over ink) has the same explicit value, so no
//!   element ever inherits a value it did not have: anything that relies on
//!   an initial value (a text run's elided black, an image) blocks it.
//! - **Classes** carry paint only: `.cN{prop:value;…}` in one `<style>` at
//!   the top of `<defs>`. A class's twins are not CSS (resvg's CSS parser
//!   drops the rest of a rule at a custom property, found by rendering):
//!   they are `<xarast:paint-class xarast:class="cN" xarast:fill-ref=…
//!   xarast:stroke-ref=…/>` right after the `<style>`. An element with a
//!   class has none of the class's properties as attributes.

use std::collections::HashMap;
use std::hash::{BuildHasherDefault, Hasher};

use super::xml::push_attr_escaped;

/// The properties a slot holds, in the order they are written.
pub(crate) const PROPS: [&str; 13] = [
    "fill",
    "fill-opacity",
    "fill-rule",
    "xarast:fill-ref",
    "stroke",
    "stroke-opacity",
    "stroke-width",
    "stroke-linecap",
    "stroke-linejoin",
    "stroke-miterlimit",
    "stroke-dasharray",
    "stroke-dashoffset",
    "xarast:stroke-ref",
];

/// Index of a property in [`PROPS`].
#[allow(missing_docs)]
pub(crate) mod p {
    pub const FILL: usize = 0;
    pub const FILL_OPACITY: usize = 1;
    pub const FILL_RULE: usize = 2;
    pub const FILL_REF: usize = 3;
    pub const STROKE: usize = 4;
    pub const STROKE_OPACITY: usize = 5;
    pub const STROKE_WIDTH: usize = 6;
    pub const LINECAP: usize = 7;
    pub const LINEJOIN: usize = 8;
    pub const MITERLIMIT: usize = 9;
    pub const DASHARRAY: usize = 10;
    pub const DASHOFFSET: usize = 11;
    pub const STROKE_REF: usize = 12;
}

const N: usize = PROPS.len();

/// Interned values, one per property; 0 = not written.
pub(crate) type Vals = [u32; N];

/// Classes need at least this many elements sharing a set…
const CLASS_MIN_USES: u32 = 8;
/// …of at least this many properties (§4.5.1 pass 5).
const CLASS_MIN_PROPS: usize = 3;

/// A multiply–rotate hasher (the `FxHash` scheme): the keys are short
/// strings and fixed arrays generated by the writer, hashed millions of
/// times per save, and flooding is not a concern for a local file.
#[derive(Default, Clone, Copy)]
pub(crate) struct Fx(u64);

impl Hasher for Fx {
    fn write(&mut self, bytes: &[u8]) {
        for c in bytes.chunks(8) {
            let mut w = [0u8; 8];
            for (d, s) in w.iter_mut().zip(c) {
                *d = *s;
            }
            self.write_u64(u64::from_le_bytes(w));
        }
    }
    fn write_u8(&mut self, i: u8) {
        self.write_u64(u64::from(i));
    }
    fn write_u32(&mut self, i: u32) {
        self.write_u64(u64::from(i));
    }
    fn write_usize(&mut self, i: usize) {
        self.write_u64(i as u64);
    }
    fn write_u64(&mut self, i: u64) {
        self.0 = (self.0.rotate_left(5) ^ i).wrapping_mul(0x51_7c_c1_b7_27_22_0a_95);
    }
    fn finish(&self) -> u64 {
        self.0
    }
}

type FxMap<K, V> = HashMap<K, V, BuildHasherDefault<Fx>>;

#[derive(Debug, Clone)]
struct Slot {
    /// Byte offset in the body where the attributes go.
    pos: usize,
    vals: Vals,
    /// The element has a foreign `class` attribute: it cannot take ours.
    no_class: bool,
    /// For a `<g>`: properties its children disagree on (bit per property).
    mixed: u16,
}

/// What kind of container a group frame is.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum GroupKind {
    /// A `<g>`: properties its children share move into it.
    Hoist,
    /// A `<g>` that must not receive properties (its foreign baggage already
    /// sets paint, a `style` or a `class`): its children keep theirs.
    Keep,
    /// A container that is not a `<g>` (a nested `<svg>`): opaque, it
    /// blocks hoisting above it.
    Block,
}

#[derive(Debug, Default)]
struct Group {
    /// The `<g>`'s own slot; `None` for [`GroupKind::Block`].
    slot: Option<usize>,
    /// [`GroupKind::Keep`].
    keep: bool,
    kids: Vec<usize>,
    /// Something in it relies on initial values (text, a foreign fragment).
    blocked: bool,
}

/// What passes 4 and 5 did, for [`super::Stats`].
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq)]
pub(crate) struct StyleStats {
    pub hoisted: usize,
    pub classes: usize,
    pub classed: usize,
}

/// The slot table.
#[derive(Debug)]
pub(crate) struct Styler {
    hoist: bool,
    classes: bool,
    /// Interned values, escaped for an attribute; index 0 is unused.
    values: Vec<Box<str>>,
    lookup: FxMap<Box<str>, u32>,
    slots: Vec<Slot>,
    groups: Vec<Group>,
    /// Class prefix, chosen not to collide with foreign class names.
    prefix: String,
    /// Slot → class number (1-based), filled by [`Styler::plan`].
    class_of: Vec<u32>,
    css: String,
    /// `<xarast:paint-class>` elements: the twins of the classes.
    twins: String,
    pub stats: StyleStats,
}

impl Styler {
    pub(crate) fn new(hoist: bool, classes: bool, prefix: String) -> Styler {
        Styler {
            hoist,
            classes,
            values: vec!["".into()],
            lookup: FxMap::default(),
            slots: Vec::new(),
            groups: Vec::new(),
            prefix,
            class_of: Vec::new(),
            css: String::new(),
            twins: String::new(),
            stats: StyleStats::default(),
        }
    }

    /// Interns a raw (unescaped) value.
    pub(crate) fn intern(&mut self, v: &str) -> u32 {
        if let Some(&i) = self.lookup.get(v) {
            return i;
        }
        let mut esc = String::with_capacity(v.len());
        push_attr_escaped(&mut esc, v);
        let i = u32::try_from(self.values.len()).unwrap_or(u32::MAX);
        self.values.push(esc.into());
        self.lookup.insert(v.into(), i);
        i
    }

    /// The raw text of an interned value (escaped).
    pub(crate) fn value(&self, i: u32) -> &str {
        self.values.get(i as usize).map_or("", |b| b)
    }

    /// Writes a set as plain attributes (no slot: inside a `<clipPath>`).
    pub(crate) fn write_inline(&self, vals: &Vals, out: &mut String) {
        for (name, &v) in PROPS.iter().zip(vals) {
            if v != 0 {
                push_attr(out, name, self.value(v));
            }
        }
    }

    /// An ink element whose start tag ends at `pos`.
    pub(crate) fn ink(&mut self, pos: usize, vals: Vals, no_class: bool) {
        let i = self.slots.len();
        self.slots.push(Slot {
            pos,
            vals,
            no_class,
            mixed: 0,
        });
        if let Some(g) = self.groups.last_mut() {
            g.kids.push(i);
        }
    }

    /// Something that relies on inherited values being the initial ones.
    pub(crate) fn block(&mut self) {
        if let Some(g) = self.groups.last_mut() {
            g.blocked = true;
        }
    }

    /// A container whose start tag ends at `pos`.
    pub(crate) fn open_group(&mut self, pos: usize, kind: GroupKind, no_class: bool) {
        let slot = (kind != GroupKind::Block).then(|| {
            self.slots.push(Slot {
                pos,
                vals: [0; N],
                no_class,
                mixed: 0,
            });
            self.slots.len() - 1
        });
        self.groups.push(Group {
            slot,
            keep: kind == GroupKind::Keep,
            ..Group::default()
        });
    }

    /// Closes the innermost container and hoists what its children share.
    pub(crate) fn close_group(&mut self) {
        let Some(g) = self.groups.pop() else {
            return;
        };
        let Some(me) = g.slot else {
            self.block();
            return;
        };
        if g.blocked {
            self.block();
            return;
        }
        if g.kids.is_empty() {
            // Draws nothing: neutral for its parent.
            return;
        }
        let mut common: Vals = [0; N];
        let mut mixed: u16 = 0;
        let mut kids = g.kids.iter().filter_map(|&k| self.slots.get(k));
        if let Some(first) = kids.next() {
            common = first.vals;
            mixed = first.mixed;
            for k in kids {
                mixed |= k.mixed;
                for (bit, (c, v)) in common.iter().zip(&k.vals).enumerate() {
                    if c != v {
                        mixed |= 1 << bit;
                    }
                }
            }
        }
        for (bit, c) in common.iter_mut().enumerate() {
            if mixed & (1 << bit) != 0 {
                *c = 0;
            }
        }
        if self.hoist && !g.keep {
            for (bit, &c) in common.iter().enumerate() {
                if c == 0 {
                    continue;
                }
                for &k in &g.kids {
                    if let Some(v) = self.slots.get_mut(k).and_then(|s| s.vals.get_mut(bit)) {
                        *v = 0;
                    }
                }
                self.stats.hoisted += g.kids.len();
            }
            if let Some(s) = self.slots.get_mut(me) {
                s.vals = common;
                s.mixed = mixed;
            }
        } else if let Some(s) = self.slots.get_mut(me) {
            // Not hoisting, the children keep their values: tell the
            // parent it cannot hoist anything the children set.
            s.mixed = mixed
                | common.iter().enumerate().fold(
                    0,
                    |m, (b, &c)| {
                        if c != 0 { m | (1 << b) } else { m }
                    },
                );
        }
        if let Some(parent) = self.groups.last_mut() {
            parent.kids.push(me);
        }
    }

    /// Pass 5: picks the classes and builds the rules.
    pub(crate) fn plan(&mut self) {
        self.class_of = vec![0; self.slots.len()];
        if !self.classes {
            return;
        }
        let mut counts: FxMap<Vals, u32> = FxMap::default();
        for s in &self.slots {
            if eligible(s) {
                *counts.entry(s.vals).or_insert(0) += 1;
            }
        }
        let mut numbers: FxMap<Vals, u32> = FxMap::default();
        for (s, c) in self.slots.iter().zip(self.class_of.iter_mut()) {
            if !eligible(s) || counts.get(&s.vals).copied().unwrap_or(0) < CLASS_MIN_USES {
                continue;
            }
            let next = u32::try_from(numbers.len()).unwrap_or(u32::MAX - 1) + 1;
            let n = *numbers.entry(s.vals).or_insert_with(|| {
                let name = format!("{}{next}", self.prefix);
                self.css.push('.');
                self.css.push_str(&name);
                self.css.push('{');
                let mut first = true;
                let mut twins = String::new();
                for ((i, &v), prop) in s.vals.iter().enumerate().zip(PROPS) {
                    let value = self.values.get(v as usize).map_or("", |b| b);
                    if v == 0 {
                        continue;
                    }
                    if i == p::FILL_REF || i == p::STROKE_REF {
                        push_attr(&mut twins, prop, value);
                        continue;
                    }
                    if !first {
                        self.css.push(';');
                    }
                    first = false;
                    self.css.push_str(prop);
                    self.css.push(':');
                    self.css.push_str(value);
                }
                self.css.push_str("}\n");
                if !twins.is_empty() {
                    self.twins.push_str("<xarast:paint-class xarast:class=\"");
                    self.twins.push_str(&name);
                    self.twins.push('"');
                    self.twins.push_str(&twins);
                    self.twins.push_str("/>\n");
                }
                next
            });
            *c = n;
            self.stats.classed += 1;
        }
        self.stats.classes = numbers.len();
    }

    /// The `<style>` element for `<defs>`, followed by the
    /// `<xarast:paint-class>` twins; empty when no class was made.
    pub(crate) fn style_element(&self) -> String {
        if self.css.is_empty() {
            return String::new();
        }
        let mut s = String::from("<style type=\"text/css\">\n");
        s.push_str(&self.css);
        s.push_str("</style>\n");
        s.push_str(&self.twins);
        s.truncate(s.trim_end().len());
        s
    }

    /// Copies `body` into `out`, expanding every slot.
    pub(crate) fn write_body(&self, body: &str, out: &mut String) {
        let mut last = 0usize;
        for (s, &class) in self.slots.iter().zip(&self.class_of) {
            if let Some(seg) = body.get(last..s.pos) {
                out.push_str(seg);
                last = s.pos;
            }
            if class != 0 {
                out.push_str(" class=\"");
                out.push_str(&self.prefix);
                out.push_str(&class.to_string());
                out.push('"');
            } else {
                self.write_inline(&s.vals, out);
            }
        }
        out.push_str(body.get(last..).unwrap_or(""));
    }
}

fn eligible(s: &Slot) -> bool {
    !s.no_class && s.vals.iter().filter(|&&v| v != 0).count() >= CLASS_MIN_PROPS
}

/// ` name="value"`, the value already escaped.
fn push_attr(out: &mut String, name: &str, escaped: &str) {
    out.push(' ');
    out.push_str(name);
    out.push_str("=\"");
    out.push_str(escaped);
    out.push('"');
}

/// A class prefix no foreign class token of the document looks like:
/// `c` (the spec's `cN`) unless baggage already uses `c<digits>`.
pub(crate) fn class_prefix<'a>(foreign_class_text: impl Iterator<Item = &'a str>) -> String {
    let tokens: Vec<&str> = foreign_class_text.flat_map(str::split_whitespace).collect();
    for p in ["c", "xc", "xrc", "xarast-c"] {
        let clash = tokens.iter().any(|t| {
            t.strip_prefix(p)
                .is_some_and(|r| !r.is_empty() && r.bytes().all(|b| b.is_ascii_digit()))
        });
        if !clash {
            return p.to_owned();
        }
    }
    "xarast-paint-c".to_owned()
}

/// The values of every `class="…"` in a raw fragment, roughly: enough to
/// steer [`class_prefix`] away from a clash.
pub(crate) fn fragment_classes(raw: &str) -> impl Iterator<Item = &str> {
    raw.match_indices("class=").filter_map(move |(i, m)| {
        let rest = raw.get(i + m.len()..)?;
        let q = rest.chars().next().filter(|c| *c == '"' || *c == '\'')?;
        let body = rest.get(1..)?;
        body.split(q).next()
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn vals(s: &mut Styler, pairs: &[(usize, &str)]) -> Vals {
        let mut v = [0; N];
        for &(i, x) in pairs {
            v[i] = s.intern(x);
        }
        v
    }

    fn render(s: &mut Styler, body: &str) -> String {
        s.plan();
        let mut out = String::new();
        s.write_body(body, &mut out);
        out
    }

    #[test]
    fn shared_values_move_to_the_group_and_others_stay() {
        let mut s = Styler::new(true, false, "c".into());
        // <g X><path A/><path B/></g>
        let body = "<g><path/><path/></g>";
        s.open_group(2, GroupKind::Hoist, false);
        let a = vals(&mut s, &[(p::FILL, "#f00"), (p::STROKE, "#000")]);
        let b = vals(&mut s, &[(p::FILL, "#0f0"), (p::STROKE, "#000")]);
        s.ink(8, a, false);
        s.ink(15, b, false);
        s.close_group();
        assert_eq!(
            render(&mut s, body),
            "<g stroke=\"#000\"><path fill=\"#f00\"/><path fill=\"#0f0\"/></g>"
        );
    }

    #[test]
    fn an_initial_value_blocks_hoisting() {
        let mut s = Styler::new(true, false, "c".into());
        s.open_group(2, GroupKind::Hoist, false);
        let a = vals(&mut s, &[(p::STROKE, "#000")]);
        s.ink(8, a, false);
        s.ink(15, [0; N], false); // relies on stroke="none"
        s.close_group();
        assert_eq!(
            render(&mut s, "<g><path/><path/></g>"),
            "<g><path stroke=\"#000\"/><path/></g>"
        );
    }

    #[test]
    fn text_blocks_its_parent_and_its_ancestors() {
        let mut s = Styler::new(true, false, "c".into());
        s.open_group(2, GroupKind::Hoist, false); // outer
        s.open_group(5, GroupKind::Hoist, false); // inner, holds text
        s.block();
        s.close_group();
        let a = vals(&mut s, &[(p::FILL, "#f00")]);
        s.ink(22, a, false);
        s.close_group();
        assert_eq!(
            render(&mut s, "<g><g><text/></g><path/></g>"),
            "<g><g><text/></g><path fill=\"#f00\"/></g>"
        );
    }

    #[test]
    fn hoisting_chains_up_through_nested_groups() {
        let mut s = Styler::new(true, false, "c".into());
        let red = vals(&mut s, &[(p::FILL, "#f00")]);
        s.open_group(2, GroupKind::Hoist, false);
        s.open_group(5, GroupKind::Hoist, false);
        s.ink(11, red, false);
        s.ink(18, red, false);
        s.close_group();
        s.ink(29, red, false);
        s.close_group();
        assert_eq!(
            render(&mut s, "<g><g><path/><path/></g><path/></g>"),
            "<g fill=\"#f00\"><g><path/><path/></g><path/></g>"
        );
    }

    #[test]
    fn eight_uses_of_three_properties_make_a_class() {
        let mut s = Styler::new(false, true, "c".into());
        let set = vals(
            &mut s,
            &[
                (p::FILL, "#fff"),
                (p::FILL_REF, "#c-6"),
                (p::STROKE, "#000"),
            ],
        );
        let small = vals(&mut s, &[(p::FILL, "#fff"), (p::STROKE, "#000")]);
        let mut body = String::new();
        for i in 0..10 {
            body.push_str("<path/>");
            s.ink(body.len() - 2, if i == 9 { small } else { set }, i == 7);
        }
        let out = render(&mut s, &body);
        assert_eq!(s.stats.classes, 1);
        assert_eq!(s.stats.classed, 8, "one opted out, one is too small");
        assert!(out.starts_with("<path class=\"c1\"/>"));
        assert!(out.ends_with("<path fill=\"#fff\" stroke=\"#000\"/>"));
        assert_eq!(
            s.style_element(),
            "<style type=\"text/css\">\n.c1{fill:#fff;stroke:#000}\n</style>\n\
             <xarast:paint-class xarast:class=\"c1\" xarast:fill-ref=\"#c-6\"/>"
        );
    }

    #[test]
    fn the_prefix_avoids_foreign_class_names() {
        assert_eq!(class_prefix(["st0 c"].into_iter()), "c");
        assert_eq!(class_prefix(["a c12"].into_iter()), "xc");
        let raw = "<rect class='c1' /><g class=\"xc3\"/>";
        assert_eq!(class_prefix(fragment_classes(raw)), "xrc");
    }
}
