[package]
name = "xarast-format"
description = "Reader and writer for the native .xarast container format"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
xarast-doc = { path = "../xarast-doc" }
