//! The tag table: every tag defined by the format, its symbolic name and
//! how the importer classifies it.
//!
//! Generated once from the master table of `docs/research/01-xar-format.md
//! §4.1`, which lists all 300 tags the original defines and how many times
//! each occurs across the 59-file corpus. Tag numbers and names are facts
//! needed for interoperability; nothing here is copied code.
//!
//! Sorted by tag, and a test proves it, because lookup is a binary search.
//!
//! Two entries are **not** from that table: `TAG_PATH_FLAGS` (111) and
//! `TAG_TEXT_FONT_SIZE` (2906). Both are real, both are documented
//! elsewhere in the same research note (§7.5 and §4.12.4), and 111 alone is
//! 10.96 % of every record in the corpus — the master table simply misses
//! them. See `docs/memory/xar-import.md`.

use crate::tags::TagClass;

/// `(tag, symbolic name, class)`, sorted by tag.
pub(crate) const TAG_TABLE: &[(u32, &str, TagClass)] = &[
    (0, "TAG_UP", TagClass::Structural),
    (1, "TAG_DOWN", TagClass::Structural),
    (2, "TAG_FILEHEADER", TagClass::Structural),
    (3, "TAG_ENDOFFILE", TagClass::Structural),
    (10, "TAG_ATOMICTAGS", TagClass::Structural),
    (11, "TAG_ESSENTIALTAGS", TagClass::Structural),
    (12, "TAG_TAGDESCRIPTION", TagClass::Structural),
    (20, "TAG_NONRENDERSECTION_START", TagClass::Ignorable),
    (21, "TAG_NONRENDERSECTION_END", TagClass::Ignorable),
    (22, "TAG_RENDERING_PAUSE", TagClass::Ignorable),
    (23, "TAG_RENDERING_RESUME", TagClass::Ignorable),
    (30, "TAG_STARTCOMPRESSION", TagClass::Structural),
    (31, "TAG_ENDCOMPRESSION", TagClass::Structural),
    (40, "TAG_DOCUMENT", TagClass::Structural),
    (41, "TAG_CHAPTER", TagClass::Structural),
    (42, "TAG_SPREAD", TagClass::Structural),
    (43, "TAG_LAYER", TagClass::Structural),
    (44, "TAG_PAGE", TagClass::Structural),
    (45, "TAG_SPREADINFORMATION", TagClass::Structural),
    (46, "TAG_GRIDRULERSETTINGS", TagClass::Ignorable),
    (47, "TAG_GRIDRULERORIGIN", TagClass::Ignorable),
    (48, "TAG_LAYERDETAILS", TagClass::Structural),
    (49, "TAG_GUIDELAYERDETAILS", TagClass::Structural),
    (50, "TAG_DEFINERGBCOLOUR", TagClass::Definition),
    (51, "TAG_DEFINECOMPLEXCOLOUR", TagClass::Definition),
    (52, "TAG_SPREADSCALING_ACTIVE", TagClass::Ignorable),
    (53, "TAG_SPREADSCALING_INACTIVE", TagClass::Ignorable),
    (60, "TAG_PREVIEWBITMAP_BMP", TagClass::Ignorable),
    (61, "TAG_PREVIEWBITMAP_GIF", TagClass::Ignorable),
    (62, "TAG_PREVIEWBITMAP_JPEG", TagClass::Ignorable),
    (63, "TAG_PREVIEWBITMAP_PNG", TagClass::Ignorable),
    (64, "TAG_PREVIEWBITMAP_TIFFLZW", TagClass::Ignorable),
    (65, "TAG_DEFINEBITMAP_BMP", TagClass::Definition),
    (66, "TAG_DEFINEBITMAP_GIF", TagClass::Definition),
    (67, "TAG_DEFINEBITMAP_JPEG", TagClass::Definition),
    (68, "TAG_DEFINEBITMAP_PNG", TagClass::Definition),
    (69, "TAG_DEFINEBITMAP_BMPZIP", TagClass::Definition),
    (70, "TAG_DEFINESOUND_WAV", TagClass::Definition),
    (71, "TAG_DEFINEBITMAP_JPEG8BPP", TagClass::Definition),
    (80, "TAG_VIEWPORT", TagClass::Ignorable),
    (81, "TAG_VIEWQUALITY", TagClass::Ignorable),
    (82, "TAG_DOCUMENTVIEW", TagClass::Ignorable),
    (85, "TAG_DEFINE_PREFIXUSERUNIT", TagClass::Definition),
    (86, "TAG_DEFINE_SUFFIXUSERUNIT", TagClass::Definition),
    (87, "TAG_DEFINE_DEFAULTUNITS", TagClass::Ignorable),
    (90, "TAG_DOCUMENTCOMMENT", TagClass::Ignorable),
    (91, "TAG_DOCUMENTDATES", TagClass::Ignorable),
    (92, "TAG_DOCUMENTUNDOSIZE", TagClass::Ignorable),
    (93, "TAG_DOCUMENTFLAGS", TagClass::Ignorable),
    (95, "TAG_NAMEGAL_DOCCOMP", TagClass::Ignorable),
    (100, "TAG_PATH", TagClass::Object),
    (101, "TAG_PATH_FILLED", TagClass::Object),
    (102, "TAG_PATH_STROKED", TagClass::Object),
    (103, "TAG_PATH_FILLED_STROKED", TagClass::Object),
    (104, "TAG_GROUP", TagClass::Object),
    (105, "TAG_BLEND", TagClass::Object),
    (106, "TAG_BLENDER", TagClass::Object),
    (107, "TAG_MOULD_ENVELOPE", TagClass::Object),
    (108, "TAG_MOULD_PERSPECTIVE", TagClass::Object),
    (109, "TAG_MOULD_GROUP", TagClass::Object),
    (110, "TAG_MOULD_PATH", TagClass::Object),
    // Not in the master table of `research/01 §4.1`, which the rest of
    // this file is generated from, but real and documented in §7.5 — and
    // 10.96 % of every record in the corpus.
    (111, "TAG_PATH_FLAGS", TagClass::Attribute),
    (112, "TAG_GUIDELINE", TagClass::Ignorable),
    (113, "TAG_PATH_RELATIVE", TagClass::Object),
    (114, "TAG_PATH_RELATIVE_FILLED", TagClass::Object),
    (115, "TAG_PATH_RELATIVE_STROKED", TagClass::Object),
    (116, "TAG_PATH_RELATIVE_FILLED_STROKED", TagClass::Object),
    (118, "TAG_PATHREF_TRANSFORM", TagClass::Object),
    (150, "TAG_FLATFILL", TagClass::Attribute),
    (151, "TAG_LINECOLOUR", TagClass::Attribute),
    (152, "TAG_LINEWIDTH", TagClass::Attribute),
    (153, "TAG_LINEARFILL", TagClass::Attribute),
    (154, "TAG_CIRCULARFILL", TagClass::Attribute),
    (155, "TAG_ELLIPTICALFILL", TagClass::Attribute),
    (156, "TAG_CONICALFILL", TagClass::Attribute),
    (157, "TAG_BITMAPFILL", TagClass::Attribute),
    (158, "TAG_CONTONEBITMAPFILL", TagClass::Attribute),
    (159, "TAG_FRACTALFILL", TagClass::Attribute),
    (160, "TAG_FILLEFFECT_FADE", TagClass::Attribute),
    (161, "TAG_FILLEFFECT_RAINBOW", TagClass::Attribute),
    (162, "TAG_FILLEFFECT_ALTRAINBOW", TagClass::Attribute),
    (163, "TAG_FILL_REPEATING", TagClass::Attribute),
    (164, "TAG_FILL_NONREPEATING", TagClass::Attribute),
    (165, "TAG_FILL_REPEATINGINVERTED", TagClass::Attribute),
    (166, "TAG_FLATTRANSPARENTFILL", TagClass::Attribute),
    (167, "TAG_LINEARTRANSPARENTFILL", TagClass::Attribute),
    (168, "TAG_CIRCULARTRANSPARENTFILL", TagClass::Attribute),
    (169, "TAG_ELLIPTICALTRANSPARENTFILL", TagClass::Attribute),
    (170, "TAG_CONICALTRANSPARENTFILL", TagClass::Attribute),
    (171, "TAG_BITMAPTRANSPARENTFILL", TagClass::Attribute),
    (172, "TAG_FRACTALTRANSPARENTFILL", TagClass::Attribute),
    (173, "TAG_LINETRANSPARENCY", TagClass::Attribute),
    (174, "TAG_STARTCAP", TagClass::Attribute),
    (175, "TAG_ENDCAP", TagClass::Attribute),
    (176, "TAG_JOINSTYLE", TagClass::Attribute),
    (177, "TAG_MITRELIMIT", TagClass::Attribute),
    (178, "TAG_WINDINGRULE", TagClass::Attribute),
    (179, "TAG_QUALITY", TagClass::Attribute),
    (180, "TAG_TRANSPARENTFILL_REPEATING", TagClass::Attribute),
    (181, "TAG_TRANSPARENTFILL_NONREPEATING", TagClass::Attribute),
    (
        182,
        "TAG_TRANSPARENTFILL_REPEATINGINVERTED",
        TagClass::Attribute,
    ),
    (183, "TAG_DASHSTYLE", TagClass::Attribute),
    (184, "TAG_DEFINEDASH", TagClass::Attribute),
    (185, "TAG_ARROWHEAD", TagClass::Attribute),
    (186, "TAG_ARROWTAIL", TagClass::Attribute),
    (187, "TAG_DEFINEARROW", TagClass::Attribute),
    (188, "TAG_DEFINEDASH_SCALED", TagClass::Attribute),
    (189, "TAG_USERVALUE", TagClass::Attribute),
    (190, "TAG_FLATFILL_NONE", TagClass::Attribute),
    (191, "TAG_FLATFILL_BLACK", TagClass::Attribute),
    (192, "TAG_FLATFILL_WHITE", TagClass::Attribute),
    (193, "TAG_LINECOLOUR_NONE", TagClass::Attribute),
    (194, "TAG_LINECOLOUR_BLACK", TagClass::Attribute),
    (195, "TAG_LINECOLOUR_WHITE", TagClass::Attribute),
    (198, "TAG_NODE_BITMAP", TagClass::Object),
    (199, "TAG_NODE_CONTONEDBITMAP", TagClass::Object),
    (200, "TAG_SQUAREFILL", TagClass::Attribute),
    (201, "TAG_SQUARETRANSPARENTFILL", TagClass::Attribute),
    (202, "TAG_THREECOLFILL", TagClass::Attribute),
    (203, "TAG_THREECOLTRANSPARENTFILL", TagClass::Attribute),
    (204, "TAG_FOURCOLFILL", TagClass::Attribute),
    (205, "TAG_FOURCOLTRANSPARENTFILL", TagClass::Attribute),
    (206, "TAG_FILL_REPEATING_EXTRA", TagClass::Attribute),
    (
        207,
        "TAG_TRANSPARENTFILL_REPEATING_EXTRA",
        TagClass::Attribute,
    ),
    (1000, "TAG_ELLIPSE_SIMPLE", TagClass::Object),
    (1001, "TAG_ELLIPSE_COMPLEX", TagClass::Object),
    (1100, "TAG_RECTANGLE_SIMPLE", TagClass::Object),
    (1101, "TAG_RECTANGLE_SIMPLE_REFORMED", TagClass::Object),
    (1102, "TAG_RECTANGLE_SIMPLE_STELLATED", TagClass::Object),
    (
        1103,
        "TAG_RECTANGLE_SIMPLE_STELLATED_REFORMED",
        TagClass::Object,
    ),
    (1104, "TAG_RECTANGLE_SIMPLE_ROUNDED", TagClass::Object),
    (
        1105,
        "TAG_RECTANGLE_SIMPLE_ROUNDED_REFORMED",
        TagClass::Object,
    ),
    (
        1106,
        "TAG_RECTANGLE_SIMPLE_ROUNDED_STELLATED",
        TagClass::Object,
    ),
    (
        1107,
        "TAG_RECTANGLE_SIMPLE_ROUNDED_STELLATED_REFORMED",
        TagClass::Object,
    ),
    (1108, "TAG_RECTANGLE_COMPLEX", TagClass::Object),
    (1109, "TAG_RECTANGLE_COMPLEX_REFORMED", TagClass::Object),
    (1110, "TAG_RECTANGLE_COMPLEX_STELLATED", TagClass::Object),
    (
        1111,
        "TAG_RECTANGLE_COMPLEX_STELLATED_REFORMED",
        TagClass::Object,
    ),
    (1112, "TAG_RECTANGLE_COMPLEX_ROUNDED", TagClass::Object),
    (
        1113,
        "TAG_RECTANGLE_COMPLEX_ROUNDED_REFORMED",
        TagClass::Object,
    ),
    (
        1114,
        "TAG_RECTANGLE_COMPLEX_ROUNDED_STELLATED",
        TagClass::Object,
    ),
    (
        1115,
        "TAG_RECTANGLE_COMPLEX_ROUNDED_STELLATED_REFORMED",
        TagClass::Object,
    ),
    (1200, "TAG_POLYGON_COMPLEX", TagClass::Object),
    (1201, "TAG_POLYGON_COMPLEX_REFORMED", TagClass::Object),
    (1212, "TAG_POLYGON_COMPLEX_STELLATED", TagClass::Object),
    (
        1213,
        "TAG_POLYGON_COMPLEX_STELLATED_REFORMED",
        TagClass::Object,
    ),
    (1214, "TAG_POLYGON_COMPLEX_ROUNDED", TagClass::Object),
    (
        1215,
        "TAG_POLYGON_COMPLEX_ROUNDED_REFORMED",
        TagClass::Object,
    ),
    (
        1216,
        "TAG_POLYGON_COMPLEX_ROUNDED_STELLATED",
        TagClass::Object,
    ),
    (
        1217,
        "TAG_POLYGON_COMPLEX_ROUNDED_STELLATED_REFORMED",
        TagClass::Object,
    ),
    (1900, "TAG_REGULAR_SHAPE_PHASE_1", TagClass::Object),
    (1901, "TAG_REGULAR_SHAPE_PHASE_2", TagClass::Object),
    (2000, "TAG_FONT_DEF_TRUETYPE", TagClass::Definition),
    (2001, "TAG_FONT_DEF_ATM", TagClass::Definition),
    (2100, "TAG_TEXT_STORY_SIMPLE", TagClass::Object),
    (2101, "TAG_TEXT_STORY_COMPLEX", TagClass::Object),
    (2110, "TAG_TEXT_STORY_SIMPLE_START_LEFT", TagClass::Object),
    (2111, "TAG_TEXT_STORY_SIMPLE_START_RIGHT", TagClass::Object),
    (2112, "TAG_TEXT_STORY_SIMPLE_END_LEFT", TagClass::Object),
    (2113, "TAG_TEXT_STORY_SIMPLE_END_RIGHT", TagClass::Object),
    (2114, "TAG_TEXT_STORY_COMPLEX_START_LEFT", TagClass::Object),
    (2115, "TAG_TEXT_STORY_COMPLEX_START_RIGHT", TagClass::Object),
    (2116, "TAG_TEXT_STORY_COMPLEX_END_LEFT", TagClass::Object),
    (2117, "TAG_TEXT_STORY_COMPLEX_END_RIGHT", TagClass::Object),
    (2150, "TAG_TEXT_STORY_WORD_WRAP_INFO", TagClass::Ignorable),
    (2151, "TAG_TEXT_STORY_INDENT_INFO", TagClass::Ignorable),
    (2200, "TAG_TEXT_LINE", TagClass::Object),
    (2201, "TAG_TEXT_STRING", TagClass::Object),
    (2202, "TAG_TEXT_CHAR", TagClass::Object),
    (2203, "TAG_TEXT_EOL", TagClass::Object),
    (2204, "TAG_TEXT_KERN", TagClass::Object),
    (2205, "TAG_TEXT_CARET", TagClass::Object),
    (2206, "TAG_TEXT_LINE_INFO", TagClass::Object),
    (2900, "TAG_TEXT_LINESPACE_RATIO", TagClass::Attribute),
    (2901, "TAG_TEXT_LINESPACE_ABSOLUTE", TagClass::Attribute),
    (2902, "TAG_TEXT_JUSTIFICATION_LEFT", TagClass::Attribute),
    (2903, "TAG_TEXT_JUSTIFICATION_CENTRE", TagClass::Attribute),
    (2904, "TAG_TEXT_JUSTIFICATION_RIGHT", TagClass::Attribute),
    (2905, "TAG_TEXT_JUSTIFICATION_FULL", TagClass::Attribute),
    // Also missing from the master table; documented in §4.12.4.
    (2906, "TAG_TEXT_FONT_SIZE", TagClass::Attribute),
    (2907, "TAG_TEXT_FONT_TYPEFACE", TagClass::Attribute),
    (2908, "TAG_TEXT_BOLD_ON", TagClass::Attribute),
    (2909, "TAG_TEXT_BOLD_OFF", TagClass::Attribute),
    (2910, "TAG_TEXT_ITALIC_ON", TagClass::Attribute),
    (2911, "TAG_TEXT_ITALIC_OFF", TagClass::Attribute),
    (2912, "TAG_TEXT_UNDERLINE_ON", TagClass::Attribute),
    (2913, "TAG_TEXT_UNDERLINE_OFF", TagClass::Attribute),
    (2914, "TAG_TEXT_SCRIPT_ON", TagClass::Attribute),
    (2915, "TAG_TEXT_SCRIPT_OFF", TagClass::Attribute),
    (2916, "TAG_TEXT_SUPERSCRIPT_ON", TagClass::Attribute),
    (2917, "TAG_TEXT_SUBSCRIPT_ON", TagClass::Attribute),
    (2918, "TAG_TEXT_TRACKING", TagClass::Attribute),
    (2919, "TAG_TEXT_ASPECT_RATIO", TagClass::Attribute),
    (2920, "TAG_TEXT_BASELINE", TagClass::Attribute),
    (3500, "TAG_OVERPRINTLINEON", TagClass::Attribute),
    (3501, "TAG_OVERPRINTLINEOFF", TagClass::Attribute),
    (3502, "TAG_OVERPRINTFILLON", TagClass::Attribute),
    (3503, "TAG_OVERPRINTFILLOFF", TagClass::Attribute),
    (3504, "TAG_PRINTONALLPLATESON", TagClass::Attribute),
    (3505, "TAG_PRINTONALLPLATESOFF", TagClass::Attribute),
    (3506, "TAG_PRINTERSETTINGS", TagClass::Ignorable),
    (3507, "TAG_IMAGESETTING", TagClass::Ignorable),
    (3508, "TAG_COLOURPLATE", TagClass::Ignorable),
    (3509, "TAG_PRINTMARKDEFAULT", TagClass::Ignorable),
    (3510, "TAG_PRINTMARKCUSTOM", TagClass::Object),
    (4000, "TAG_VARIABLEWIDTHFUNC", TagClass::Attribute),
    (4001, "TAG_VARIABLEWIDTHTABLE", TagClass::Attribute),
    (4002, "TAG_STROKETYPE", TagClass::Attribute),
    (4003, "TAG_STROKEDEFINITION", TagClass::Definition),
    (4004, "TAG_STROKEAIRBRUSH", TagClass::Attribute),
    (4010, "TAG_NOISEFILL", TagClass::Attribute),
    (4011, "TAG_NOISETRANSPARENTFILL", TagClass::Attribute),
    (4012, "TAG_MOULD_BOUNDS", TagClass::Ignorable),
    (4013, "TAG_PATHREF_IDENTICAL", TagClass::Object),
    (4014, "TAG_PATHREF_TRANSLATE", TagClass::Object),
    (4015, "TAG_EXPORT_HINT", TagClass::Ignorable),
    (4020, "TAG_WEBADDRESS", TagClass::Attribute),
    (4021, "TAG_WEBADDRESS_BOUNDINGBOX", TagClass::Attribute),
    (4030, "TAG_LAYER_FRAMEPROPS", TagClass::Ignorable),
    (4031, "TAG_SPREAD_ANIMPROPS", TagClass::Ignorable),
    (4040, "TAG_WIZOP", TagClass::Ignorable),
    (4041, "TAG_WIZOP_STYLE", TagClass::Definition),
    (4042, "TAG_WIZOP_STYLEREF", TagClass::Ignorable),
    (4050, "TAG_SHADOWCONTROLLER", TagClass::Object),
    (4051, "TAG_SHADOW", TagClass::Object),
    (4052, "TAG_BEVEL", TagClass::Object),
    (4053, "TAG_BEVATTR_INDENT", TagClass::Ignorable),
    (4054, "TAG_BEVATTR_LIGHTANGLE", TagClass::Ignorable),
    (4055, "TAG_BEVATTR_CONTRAST", TagClass::Ignorable),
    (4056, "TAG_BEVATTR_TYPE", TagClass::Ignorable),
    (4057, "TAG_BEVELINK", TagClass::Object),
    (4060, "TAG_BLENDER_CURVEPROP", TagClass::Ignorable),
    (4061, "TAG_BLEND_PATH", TagClass::Object),
    (4062, "TAG_BLENDER_CURVEANGLES", TagClass::Ignorable),
    (4063, "TAG_GROUPTRANSP", TagClass::Ignorable),
    (4064, "TAG_CACHEBMP", TagClass::Ignorable),
    (4065, "TAG_CACHEDNODESGROUP", TagClass::Ignorable),
    (4066, "TAG_CONTOURCONTROLLER", TagClass::Object),
    (4067, "TAG_CONTOUR", TagClass::Object),
    (4070, "TAG_SETSENTINEL", TagClass::Ignorable),
    (4071, "TAG_SETPROPERTY", TagClass::Ignorable),
    (4072, "TAG_BLENDPROFILES", TagClass::Ignorable),
    (4073, "TAG_BLENDERADDITIONAL", TagClass::Ignorable),
    (4074, "TAG_NODEBLENDPATH_FILLED", TagClass::Ignorable),
    (4075, "TAG_LINEARFILLMULTISTAGE", TagClass::Attribute),
    (4076, "TAG_CIRCULARFILLMULTISTAGE", TagClass::Attribute),
    (4077, "TAG_ELLIPTICALFILLMULTISTAGE", TagClass::Attribute),
    (4078, "TAG_CONICALFILLMULTISTAGE", TagClass::Attribute),
    (4079, "TAG_BRUSHATTR", TagClass::Attribute),
    (4080, "TAG_BRUSHDEFINITION", TagClass::Definition),
    (4081, "TAG_BRUSHDATA", TagClass::Attribute),
    (4082, "TAG_MOREBRUSHDATA", TagClass::Attribute),
    (4083, "TAG_MOREBRUSHATTR", TagClass::Attribute),
    (4084, "TAG_CLIPVIEWCONTROLLER", TagClass::Object),
    (4085, "TAG_CLIPVIEW", TagClass::Object),
    (4086, "TAG_FEATHER", TagClass::Attribute),
    (4087, "TAG_BARPROPERTY", TagClass::Ignorable),
    (4088, "TAG_SQUAREFILLMULTISTAGE", TagClass::Attribute),
    (4102, "TAG_EVENMOREBRUSHDATA", TagClass::Attribute),
    (4103, "TAG_EVENMOREBRUSHATTR", TagClass::Attribute),
    (4104, "TAG_TIMESTAMPBRUSHDATA", TagClass::Attribute),
    (4105, "TAG_BRUSHPRESSUREINFO", TagClass::Attribute),
    (4106, "TAG_BRUSHPRESSUREDATA", TagClass::Attribute),
    (4107, "TAG_BRUSHATTRPRESSUREINFO", TagClass::Attribute),
    (4108, "TAG_BRUSHCOLOURDATA", TagClass::Attribute),
    (4109, "TAG_BRUSHPRESSURESAMPLEDATA", TagClass::Attribute),
    (4110, "TAG_BRUSHTIMESAMPLEDATA", TagClass::Attribute),
    (4111, "TAG_BRUSHATTRFILLFLAGS", TagClass::Attribute),
    (4112, "TAG_BRUSHTRANSPINFO", TagClass::Attribute),
    (4113, "TAG_BRUSHATTRTRANSPINFO", TagClass::Attribute),
    (4114, "TAG_DOCUMENTNUDGE", TagClass::Ignorable),
    (4115, "TAG_BITMAP_PROPERTIES", TagClass::Ignorable),
    (4116, "TAG_DOCUMENTBITMAPSMOOTHING", TagClass::Ignorable),
    (4117, "TAG_XPE_BITMAP_PROPERTIES", TagClass::Ignorable),
    (4118, "TAG_DEFINEBITMAP_XPE", TagClass::Definition),
    (4119, "TAG_CURRENTATTRIBUTES", TagClass::Object),
    (4120, "TAG_CURRENTATTRIBUTEBOUNDS", TagClass::Ignorable),
    (4121, "TAG_LINEARFILL3POINT", TagClass::Attribute),
    (4122, "TAG_LINEARFILLMULTISTAGE3POINT", TagClass::Attribute),
    (4123, "TAG_LINEARTRANSPARENTFILL3POINT", TagClass::Attribute),
    (4124, "TAG_DUPLICATIONOFFSET", TagClass::Ignorable),
    (4125, "TAG_LIVE_EFFECT", TagClass::Object),
    (4126, "TAG_LOCKED_EFFECT", TagClass::Object),
    (4127, "TAG_FEATHER_EFFECT", TagClass::Object),
    (4128, "TAG_COMPOUNDRENDER", TagClass::Ignorable),
    (4129, "TAG_OBJECTBOUNDS", TagClass::Ignorable),
    (4130, "TAG_DIMENSION", TagClass::Ignorable),
    (4131, "TAG_SPREAD_PHASE2", TagClass::Object),
    (4132, "TAG_CURRENTATTRIBUTES_PHASE2", TagClass::Object),
    (4134, "TAG_SPREAD_FLASHPROPS", TagClass::Ignorable),
    (4135, "TAG_PRINTERSETTINGS_PHASE2", TagClass::Ignorable),
    (4136, "TAG_DOCUMENTINFORMATION", TagClass::Ignorable),
    (4137, "TAG_CLIPVIEW_PATH", TagClass::Ignorable),
    (4138, "TAG_DEFINEBITMAP_PNG_REAL", TagClass::Ignorable),
    (4200, "TAG_TEXT_TAB", TagClass::Ignorable),
    (4201, "TAG_TEXT_LEFT_INDENT", TagClass::Attribute),
    (4202, "TAG_TEXT_FIRST_INDENT", TagClass::Attribute),
    (4203, "TAG_TEXT_RIGHT_INDENT", TagClass::Attribute),
    (4204, "TAG_TEXT_RULER", TagClass::Attribute),
    (4205, "TAG_TEXT_STORY_HEIGHT_INFO", TagClass::Ignorable),
    (4206, "TAG_TEXT_STORY_LINK_INFO", TagClass::Ignorable),
    (4207, "TAG_TEXT_STORY_TRANSLATION_INFO", TagClass::Ignorable),
];
