[package]
name = "xarast-text"
description = "Font handling, shaping and text layout for Xarast"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
xarast-geom = { path = "../xarast-geom" }
