//! Every image format through the `xarast-image` façade, with tight limits.
//!
//! The first byte picks the entry point: the sniffing façade (`probe` then
//! `decode`), or the legacy `.xar` wrapper with a tag and a palette taken
//! from the input, which reaches the headerless DIB, BMPZIP inflation and
//! the 8 bpp palette snap. Seeds are generated by
//! `cargo run -p xarast-image --example fuzz_seeds -- <dir>`.
//!
//! Invariants:
//!
//! 1. **Never panic, never exceed the limits.** No input may allocate past
//!    `DecodeLimits::tight()` (libFuzzer's `-malloc_limit_mb` catches a
//!    decoder that does) or run past its wall clock.
//! 2. **A success is well formed**: `width × height × 4` bytes, within the
//!    declared limits, every colour channel ≤ alpha (premultiplied), and the
//!    straight conversion premultiplies back to the same bytes.

#![no_main]

use libfuzzer_sys::fuzz_target;
use xarast_image::{DecodeLimits, DecodedImage, decode, pixels::premultiply, probe, xar};

const TAGS: [u32; 7] = [60, 65, 66, 67, 68, 69, 71];

fn check(d: &DecodedImage, limits: &DecodeLimits) {
    let (w, h) = (d.data.width, d.data.height);
    assert!(w > 0 && h > 0);
    assert!(w <= limits.max_dimension && h <= limits.max_dimension);
    assert!(u64::from(w) * u64::from(h) <= limits.max_pixels);
    assert_eq!(d.data.pixels.len(), w as usize * h as usize * 4);
    assert_eq!((d.info.pixel_width, d.info.pixel_height), (w, h));
    for p in d.data.pixels.as_chunks::<4>().0 {
        assert!(
            p[0] <= p[3] && p[1] <= p[3] && p[2] <= p[3],
            "not premultiplied"
        );
    }
    let straight = d.data.to_straight_rgba8();
    for (s, p) in straight
        .as_chunks::<4>()
        .0
        .iter()
        .zip(d.data.pixels.as_chunks::<4>().0)
    {
        for i in 0..3 {
            assert_eq!(premultiply(s[i], s[3]), p[i]);
        }
    }
}

fuzz_target!(|data: &[u8]| {
    let Some((&mode, rest)) = data.split_first() else {
        return;
    };
    let limits = DecodeLimits::tight();
    if mode & 3 == 0 {
        // The `.xar` wrapper: tag, palette length, palette, image.
        let Some((&sel, rest)) = rest.split_first() else {
            return;
        };
        let tag = TAGS[usize::from(sel) % TAGS.len()];
        let Some((&n, rest)) = rest.split_first() else {
            return;
        };
        let n = usize::from(n % 17).min(rest.len() / 3);
        let (pal, image) = rest.split_at(n * 3);
        let palette: Vec<[u8; 3]> = pal.as_chunks::<3>().0.to_vec();
        if let Ok(d) = xar::decode_xar_bitmap(tag, image, &palette, &limits) {
            check(&d, &limits);
        }
    } else {
        let _ = probe(rest);
        if let Ok(d) = decode(rest, &limits) {
            check(&d, &limits);
        }
    }
});
